name: CI

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install python dependencies
        run: pip3 install tqdm
      - name: Update the debian listing
        run: python3 update.py
      - name: Check if stuff is changed
        run: |
          if [[ `git status --porcelain hashes.txt` ]]; then 
            echo "CHANGED=1" >> $GITHUB_ENV
            TAG="$(date +"%Y-%M-%dT%H%m%S")"
            echo "TAG=$TAG" >> $GITHUB_ENV
            echo "Changes detected; will need to commit & release as tag $TAG"
          else
            echo "CHANGED=0" >> $GITHUB_ENV
            echo "No changes detected"
          fi
      
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'hashes.txt'
          message: 'Your commit message'
          pathspec_error_handling: exitImmediately
        if: ${{env.CHANGED == 1}}
      
      - uses: ChanTsune/release-with-commit@v2.3.0
        with:
          regexp: ".*"
          release_name: "${{env.TAG}}"
          tag_name: "${{env.TAG}}"
          draft: false
          prerelease: false
        if: ${{env.CHANGED == 1}}
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
